### ISSUE TITLE
Judet cu nr 80

### ISSUE THREAD

**Issue by lvalics** [vimishor/cnp-spec#5]
Este posibil sa avem judet cu nr 80? Persoana este nascuta in Republica Moldova cu cetatenie RO.

**Comment by vimishor** [comment]
Cifrele 7 (_sex masculin_) și 8 (_sex feminin_) de la începutul unui C.N.P. sunt rezervate pentru persoanele rezidente, iar următoarele două cifre din C.N.P. sunt ultimele două cifre din anul nașterii.

În cazul de față presupun că este vorba despre o femeie născută între 2000 și 2009.

Citește articolul de pe [wikipedia](https://ro.wikipedia.org/wiki/Cod_numeric_personal_(Rom%C3%A2nia)#S) pentru mai multe amănunte.
